default:
    image: fkrull/multi-python

variables:
  BASEPYTHON: "python3.9"

before_script:
    - $BASEPYTHON -V  # Print out python version for debugging
    - $BASEPYTHON -m venv env
    - source env/bin/activate

run:
  script:
    - tox
  artifacts:
    when: always
    reports:
      junit: report.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)
