default:
    image: fkrull/multi-python


before_script:
    - python -V  # Print out python version for debugging
    - python -m venv env
    - pip install -r dev-requirements.txt
    - source env/bin/activate


run:
  script:
    - tox
